### ISSUE TITLE
When commit has errors the message say OK

### ISSUE THREAD

**Issue by castocolina** [walmartdigital/commit-message-formatter#6]
Having project with lint/test errors and add [husky](https://github.com/typicode/husky) (npm run lint && npm run test)
Usin git 

> git commit -m "message"

The command execute my hooks and prevent commit/push when execution result has errors.

When use **cmf**, no execute commit but say is OK.

**Comment by Rodrigonavarro23** [comment]
Thank you Casto, this is because git command call  was not verifiying the successfully execution of command

**Comment by castocolina** [comment]
Check issue #9 please
