### ISSUE TITLE
Please show error for linter

### ISSUE THREAD

**Issue by castocolina** [walmartdigital/commit-message-formatter#9]
When my commit have linter errors, warnings or any output isn't displayed

![image](https://user-images.githubusercontent.com/12010427/55262167-bd17f700-524b-11e9-94b1-8235564a2db8.png)

**Comment by Rodrigonavarro23** [comment]
Hi Casto, warning is not an error, is the way you have configured your eslint rules, but we will incorporate StdErr writer to command output so you can be able to see this kind of output.

**Comment by Rodrigonavarro23** [comment]
Added on commit 1c64f5400e1381f594398a5670c4729692d1b6bb
